{% set name = "aws-eventstream" %}
{% set version = "1.3.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: f1434cc03ab2248756eb02cfa45e900e59a061d7fbdc4a9fd82a5dd23d796d3f

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Amazon Web Services event stream library. Decodes and encodes binary stream under `vnd.amazon.event-stream` content-type

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/aws/aws-sdk-ruby/tree/master/gems/{{ name }}

extra:
  recipe-maintainers:
    - conda-forge/ruby
    - pierrsc
