travis:
  secure:
    BINSTAR_TOKEN: gsVyC9GmCAtYDTJukZWg8zgTGXHTWpKE9XrX963n9GfuxY3u5Cvm8X+zVMdC2hfzIxspBOkvL9m7cRlgHfS/4U+XKcIXOw+vsHPjn+CFrxoUQQtCGaVesqWMnT6ysX02fMx/Igby1u9R/qM38gliiF/02yOq6w+ss1lGG+bj/f0KXh0yD/BAXiM2x1AoW7mqiqxS2O/3tC5vswcqCGJ1mfavAln41315BFHTB8fcEfyLNEhb46IV2K0Lv/jjhgr4QJsT+Z5+WkBFvXpNlNU5wKYzOugjYL95TbBFTK2oLC3ALHoaCzs+/z9oKWsgeDOl/V04TJMDfPRJQnTixNHMLnEzodDiKI/uIA0S10eqTQT3VdvhJnlvXcJEBj1nOyYmhUA5IedlgTAp43epfRaR2K0guQZN+0Uxa0YpwSvAv4fEWkpYPhfyySb+3blAP/vqLoBY/4lniu4V7e9dnwLO91oVCW4pGhD2bfoe5NrRv8Dnoojy8ii64Avp/GLaLNkD0mr1IJN10uNcgK4ZFrjJ7hWb8mWpyb1pHiONJ5ttD55YShZVZrB+pcxAUKn7heCA5A+VbivceL0/Wv70VNSb1FojUHB2/+fTMUSqjugKEc4RCBv0tw/L9BN3ALOMrzfrC7asZoiux7noHzXP/HfG3k2hQUBcwXj6bVvJ5KaeIEM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
