travis:
  secure:
    BINSTAR_TOKEN: noWdg+zk2+7U1A5BdKz1PAYF9/UHK8mQ9yzwAQecj/s1Ruwy90qp1Dga6FNzTPRecN1bO+vwyiuwDJpeV8IHH/3WskjEfbfPs37Io6rvbzk7JWksY1WSBQf1lOpsq/ttAHW5NX9RnaqT6PH3N2BIswG+HfDNCDIfsi1vhqz1KmiAW8T9yllt39iXgkzoGvU6Vb1QKiNUGy78rYX25Fd12oVnsMnL/PbYK3RMVSgGS2CUi6of+t+38oKlnFeaZfDfF0l9ruTf12XLGVhLUaavZ6GptmShyMHnPMRNEvrr/ZqUKFeu9vhxKX2MtETn1bsnCrwJWAY/2UXQkFB0frnhk83Jv8MxyFNYPNjiWe1Tr+ms0T9fbDayUAz+q6ZV78jeMPhWydQBb/KLZtHGYUuCN/wfbeoDwVbRkC4M5WuWkUQ9ZJPkaXomUCCEVL+v3jrBdxTEiYcBqsoM9ogQekCKX4x/DMw8E9jBjQ5YEc8ga92bN1gMoiKdtwYh1MSG06HhGdzTy5yST7ju3C0roy/q1hKyhtdBJ4x/kOsH6XgjMicEZnPaQlHjHkgCj38CUw2OPZGd/om1+UhesIDJcWez2juhJ5gv/qrXyY/2oEfUVQmpKU1GXGX7h4l0M6dN0pAadeDnssqyNm6W5BPIESAH+AmZtr+eZpO5unHpydUR9s4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
